---
name: Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  rake_checks:
    name: Rake Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current PR
        uses: actions/checkout@v4
      - name: Install Ruby version 3.3
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true
      - name: Validate code
      - run: |
        bundle exec rake rubocop --trace
        bundle exec rake -T | grep vox:build
        bundle exec rake -T | grep vox:promote
        bundle exec rake -T | grep vox:tag
        bundle exec rake -T | grep vox:upload
        bundle exec rake config:print
